### ISSUE TITLE
cctools and iOS SDK

### ISSUE THREAD

**Issue by teras** [tpoechtrager/cctools-port#10]
Is it possible to give some more information on how to obtain the iOS SDK?
I am an OSX user and developer but I don't know the exact format of the archive.

In your other project (osxcross) you provide a proper script to fetch it from an installed Xcode (or from a downloaded DMG). Unfortunately not here.

PS: I think these two projects overlap? Although I've managed to properly compile an OSX application with the other tools, with this tool the documentation is sparse and I didn't have any luck.

**Comment by tpoechtrager** [comment]
I made the iOS toolchain more or less only because of: https://github.com/tpoechtrager/cctools-port/issues/6#issuecomment-68175225.

I know the iOS toolchain is very minimalistic - but good enough to compile most things.
OSXCross is already time consuming enough.

Now, to answer your question, you can find instructions here:

https://github.com/tpoechtrager/osxcross/issues/45#issuecomment-138351002
https://github.com/tpoechtrager/osxcross/issues/46

**Comment by dmigous** [comment]
@teras I use iOS SDK downloaded from here http://iphone.howett.net/sdks/.
