### ISSUE TITLE
build.sh does not work with iOS SDK >= 9.0

### ISSUE THREAD

**Issue by vnen** [tpoechtrager/cctools-port#13]
The script relies on the location of `libSystem.dylib` which is not available in newer SDKs. The file was replaced by `libSystem.tbd` which then should be used as a fallback (or the opposite, with the `.tbd` being default and falling back for the `.dylib`.)

Since this is only used to find the directory, the script does work fine with such change.

**Comment by tpoechtrager** [comment]
Should be fixed.

**Comment by vnen** [comment]
Thanks a lot!

**Comment by dmigous** [comment]
does cctools-port with ios SDK >= 9.0 works on Linux? Because of .tbd files seems no `-llib` can be found (e.g. `-lm`, `-lz` ...)

**Comment by vnen** [comment]
@dmigous I successfully compiled the [Godot Engine](https://godotengine.org) with this, so I guess it works fine.

**Comment by dmigous** [comment]
@vnen thanks for response. 
can you please tell:
1. on what Linux distro & version did you build
2. clang version
3. did you use just usual flags like `-lz`, or pointed the absolute path to `libz.tbd` (because when I pass the absolute path to .libz.tbd it works). But using `-L` and `-l` flags it doesn't. While when I just replace content of my iPhoneOS.sdk folder with files from 8.4 SDK where same folder structure and just .dylib files, then build works fine using `-L` and `-l` flags.

**Comment by vnen** [comment]
I'm far from my machine now, but IIRC I built it in Arch Linux with Clang 3.7 (or maybe 3.8). As I said, used only to compile Godot and looking at the [build config file](https://github.com/godotengine/godot/blob/master/platform/iphone/detect.py) there's no `-l` nor `-L`  flag.

I think you should open a new issue here for your problem.
